sessoes = [
    {
        "id_sessao": 1,
        "titulo_filme": "O senhor dos anéis: A sociedade do anel",
        "sala": "Sala 1",
        "horario": "19:00",
        "assentos": [
            {"id": "A-01", "disponivel": True},
            {"id": "A-02", "disponivel": True},
            {"id": "A-03", "disponivel": True},
            {"id": "A-04", "disponivel": True},
            {"id": "A-05", "disponivel": True},
            {"id": "A-06", "disponivel": True},
            {"id": "A-07", "disponivel": True},
            {"id": "A-08", "disponivel": True},
            {"id": "A-09", "disponivel": True},
            {"id": "A-10", "disponivel": True},
        ],
    },
    {
        "id_sessao": 2,
        "titulo_filme": "Harry Potter e a pedra filosofal",
        "sala": "Sala 2",
        "horario": "20:00",
        "assentos": [
            {"id": "B-01", "disponivel": True},
            {"id": "B-02", "disponivel": True},
            {"id": "B-03", "disponivel": True},
            {"id": "B-04", "disponivel": True},
            {"id": "B-05", "disponivel": True},
            {"id": "B-06", "disponivel": True},
            {"id": "B-07", "disponivel": True},
            {"id": "B-08", "disponivel": True},
            {"id": "B-09", "disponivel": True},
            {"id": "B-10", "disponivel": True},
        ],
    },
    {
        "id_sessao": 3,
        "titulo_filme": "Monstros S.A.",
        "sala": "Sala 3",
        "horario": "18:30",
        "assentos": [
            {"id": "C-01", "disponivel": True},
            {"id": "C-02", "disponivel": True},
            {"id": "C-03", "disponivel": True},
            {"id": "C-04", "disponivel": True},
            {"id": "C-05", "disponivel": True},
            {"id": "C-06", "disponivel": True},
            {"id": "C-07", "disponivel": True},
            {"id": "C-08", "disponivel": True},
            {"id": "C-09", "disponivel": True},
            {"id": "C-10", "disponivel": True},
        ],
    },
    {
        "id_sessao": 4,
        "titulo_filme": "Onze homens e um segredo",
        "sala": "Sala 4",
        "horario": "21:00",
        "assentos": [
            {"id": "D-01", "disponivel": True},
            {"id": "D-02", "disponivel": True},
            {"id": "D-03", "disponivel": True},
            {"id": "D-04", "disponivel": True},
            {"id": "D-05", "disponivel": True},
            {"id": "D-06", "disponivel": True},
            {"id": "D-07", "disponivel": True},
            {"id": "D-08", "disponivel": True},
            {"id": "D-09", "disponivel": True},
            {"id": "D-10", "disponivel": True},
        ],
    },
    {
        "id_sessao": 5,
        "titulo_filme": "Vanilla Sky",
        "sala": "Sala 5",
        "horario": "22:00",
        "assentos": [
            {"id": "E-01", "disponivel": True},
            {"id": "E-02", "disponivel": True},
            {"id": "E-03", "disponivel": True},
            {"id": "E-04", "disponivel": True},
            {"id": "E-05", "disponivel": True},
            {"id": "E-06", "disponivel": True},
            {"id": "E-07", "disponivel": True},
            {"id": "E-08", "disponivel": True},
            {"id": "E-09", "disponivel": True},
            {"id": "E-10", "disponivel": True},
        ],
    },
]
